output-class: SubLocalizations
synthetic-package: false
arb-dir: lib/src/l10n
output-dir: ./lib/src/l10n/generated/
template-arb-file: intl_vi.arb
output-localization-file: sub_localizations.dart
resource-file: lib/src/l10n/localizations.csv