// Mocks generated by Mockito 5.4.2 from annotations
// in mobilehub_bloc/test/gen_mock/mock_object.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'mock_object.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ServiceGetList].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceGetList extends _i1.Mock implements _i2.ServiceGetList {
  MockServiceGetList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> getListingString() => (super.noSuchMethod(
        Invocation.method(
          #getListingString,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);
  @override
  _i3.Future<List<String>> getListingStringParam1(int? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListingStringParam1,
          [param],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);
}
